### PR TITLE
Added "import" to hscript

### PR DESCRIPTION
**Pull request by JustJasonLol**
adds a function to hscript which allows you to add files to your script without using the source code

example:
image

### CODE REVIEW

**Comment by BeastlyGhost** [comment]
this is already available on SScript by default

**Comment by JustJasonLol** [comment]
> this is already available on SScript by default

interesting, thx for the info

**Comment by BeastlyGabi** [comment]
just go to the beginning of your script and use the import like you'd normally on a haxe source file

**Comment by JustJasonLol** [comment]
👍

**Pull request closed without merging**
